repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Optional: Fix to a specific version.
    rev: 'v0.11.11'
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix] # Automatically fix what it can
    # Run the formatter.
    -   id: ruff-format